words = [
    "astro",
    "autocmds",
    "autoindent",
    "autopairs",
    "autotrigger",
    "birb",
    "breakindent",
    "bufnr",
    "cjs",
    "completeopt",
    "cssls",
    "cssmodules",
    "cursorline",
    "esc",
    "expandtab",
    "gitcommit",
    "gofmt",
    "golangci",
    "gopls",
    "grd",
    "gre",
    "gri",
    "grr",
    "grt",
    "hlsearch",
    "ignorecase",
    "inccommand",
    "incsearch",
    "jsonls",
    "keymaps",
    "mapleader",
    "maplocalleader",
    "menuone",
    "nargs",
    "netrw",
    "nixd",
    "nixfmt",
    "nohl",
    "nop",
    "noselect",
    "nvim",
    "prettierd",
    "pumborder",
    "pylsp",
    "relativenumber",
    "scrolloff",
    "shiftwidth",
    "showbreak",
    "showmatch",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "stylelint",
    "stylelintrc",
    "stylua",
    "subword",
    "swapfile",
    "tabstop",
    "taplo",
    "textobject",
    "textobjects",
    "timeoutlen",
    "undofile",
    "updatetime",
    "vimgrep",
    "vtsls",
    "winborder",
    "yamlls",
]
